spring:
    application:
        name: eureka-server
server:
    port: 1113
eureka:
    instance:
        hostname: cluster2
    client:
        serviceUrl:
            defaultZone: http://cluster1:1112/eureka/