spring:
  application:
    name: config-server
# Git管理配置
  cloud:
    config:
      server:
        git:
          uri: https://github.com/wa1ker77/spring-cloud-sample/
          search-paths: spring_cloud_config_repository
          username:
          password:
server:
  port: 7001
# 配置服务注册中心
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/
