spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/didispace/SpringCloud-Learning/
          search-paths: spring_cloud_in_action/config-repo
          username:
          password:
server:
  port: 1121